// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace InsertGuid
{
    internal sealed partial class Vsix
    {
        public const string Id = "9def4441-acfd-4dd6-bffd-4531a57dee37";
        public const string Name = "Insert Guid";
        public const string Description = @"Makes it super easy to insert a new GUID into any editor and input field";
        public const string Language = "en-US";
        public const string Version = "1.3";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
    }
}
