// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.210
// </auto-generated>
// ------------------------------------------------------------------------------
namespace InsertGuid
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidInsertGuidCommandPackageString = "40121d57-9e96-4986-becb-fe05620e79a8";
        public const string guidInsertGuidCommandPackageCmdSetString = "1440eeb0-81f7-4062-b88a-99ca97249e33";
        public static Guid guidInsertGuidCommandPackage = new Guid(guidInsertGuidCommandPackageString);
        public static Guid guidInsertGuidCommandPackageCmdSet = new Guid(guidInsertGuidCommandPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int InsertGuidCommandId = 0x0100;
    }
}
