// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace InsertGuid
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidInsertGuidPackageString = "40121d57-9e96-4986-becb-fe05620e79a8";
        public static Guid guidInsertGuidPackage = new Guid(guidInsertGuidPackageString);

        public const string guidInsertGuidCmdSetString = "1440eeb0-81f7-4062-b88a-99ca97249e33";
        public static Guid guidInsertGuidCmdSet = new Guid(guidInsertGuidCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int cmdInsertGuid = 0x0100;
    }
}